### PR TITLE
Added suggestions for missing parameters

### PR DESCRIPTION
**Pull request by felippewi**
Hi everyone, as promised, here are a couple of suggestions for additions to the ontology.
For more information, you can check the reference to ONE's T&Cs in the new tab of this file: [ https://docs.google.com/spreadsheets/d/1H1-yiDOT-F6qSLAob_8BmcxKPk4qXcSwIF0q9ff1ljI/edit#gid=357474690](url)

The descriptions for the coverages are not yet correct.
Let me know if you have any questions.

Best, 
Felippe

### CODE REVIEW

**Comment by bponleitner** [comment]
Hi @felippewi, thank you for your suggestions and the reference-file! We will look into it as soon as possible.

**Comment by bponleitner** [comment]
Hi @felippewi! 
Please take a look at the updated schema! I integrated your suggestions to the best of my ability.
Some remarks from my side:

- about the missing coverages: two of them already exist in the ontology:
-- "product.motor.coverage.comprehensive.replacement-of-parts-without-deduction.is-included"  -> in Ontology: "product.motor.coverage.comprehensive.new-for-old-without-deduction.is-included"
-- "product.motor.coverage.comprehensive.fully.own-vehicle-self-damage.sum-insured" -> in Ontology: product.motor.coverage.comprehensive.fully.vehicle-damage-accident.sum-insured; 
However, in this case I like your suggestion better. Thus, I’d like to change the parameter-name in the Ontology, if that’s ok. 
- Also, I included the other-driver-option as additional coverage (product.motor.coverage.additional-driver.is-included)
- object.vehicle.number-plate is changed to license-plate
- The only parameter not included in the ontology is the one capturing the age of the youngest age. As we discussed before with the guys from ONE (about a year ago), this information should be modelled using the object.vehicle.driver.birthdate-parameter.

Please let me know if the changes work for you!

**Comment by felippewi** [comment]
Hi @bponleitner,

all changes make sense to me. I think even the changes to already existing parameters should not have an impact on the products we've already configured. 
Acknowledging that some parameters are in the ontology but are named differently, I'd suggest having a way to describe each parameter. I believe that not only me but also prospective insurers will be confused with or will overlook the parameters in the ontology that they search for.

What do you think @koen-verduijn?

**Comment by bponleitner** [comment]
@felippewi thanks for your quick response! I agree we need to add descriptions of the coverages to the ontology. We are working on this topic. 
I'd merge the pull request if there are no objections from your side.

**Pull request merged**
