### PR TITLE
Update household.json

### PR DESCRIPTION
**Pull request by koen-verduijn**
Added new coverages and inputs to match insurance product.

### CODE REVIEW

**Comment by bponleitner** [comment]
Hi @koen-verduijn ,
thank you for your updates! I reviewed your changes and made the following  modifications:

- In order to keep the coverage parameters consistent, I modified the names of the parameters for the 'outdoor'- and the 'elemental-damage'-coverage a bit.
- There already exists a parameter to capture the max.amount insured by all household-contents-coverages: product.household.coverage.household-contents.sum-insured. Thus, I removed the parameter you added from the schema.

Please let us know when you are finished with updating the household.json. Then we will merge the changes.

**Comment by koen-verduijn** [comment]
Agree with your changes to outdoor and elemental damage. With the overall household sum insured. This is not just within the household contents, its also outdoor and a bike. So I do think that sum insured needs to be added. Could you not remove it and then still merge it to master?

**Comment by koen-verduijn** [comment]
I looked through the parameters again and I dont get the naming completely @bponleitner. What is the rationale behind:
product.household.coverage.household-contents why is the household-contents needed? What does .household-contents allow the ontology to do?

**Comment by koen-verduijn** [comment]
to be covered in only household content file

**Pull request closed without merging**
