### PR TITLE
Add vehicle and vehicle.driver params

### PR DESCRIPTION
**Pull request by felippewi**
Hi @bponleitner, happy new year first of all! A bit late but we didn't happen to see each other lately :)

I have a couple of suggestions for new params for the motor ontology.
Please review. If there any questions, don't hesitate to reach out!

Best, Felippe

### CODE REVIEW

**Comment by bponleitner** [comment]
Hallo @felippewi , happy new year for you, too! 

Thank you for your suggestions, I will take a look at it! 
One question in advance: what do you mean exactely by "model-begin" and "model-end" for the vehicle? 

Best, Bettina

**Comment by felippewi** [comment]
Hi Bettina,

It's the model's import/sale begin and end. The format used in the "Eurotax" dataset created by Autovista Group proposes this format "YYYYMM" / "199806".

Best,
Felippe

**Comment by bponleitner** [comment]
> It's the model's import/sale begin and end. The format used in the "Eurotax" dataset created by Autovista Group proposes this format "YYYYMM" / "199806".

Hi Felippe,
Thank you for the explanation! 
Best, Bettina

**Comment by bponleitner** [comment]
Hi @felippewi ,
I updated the motor-product-schema with respect to the properties you suggested. 

A few comments:
- instead of _eurotax-id_ I used the more general (and internationally unique) _vin_ = Vehicle Identification Number.
- for _body-type_, _fuel-type_ and _transmission-type_ I used the value-list you sent me as a basis and tried to find corresponding EN-values.  However, I omitted the transmission value "automat stufenlos/sequentiell" since in my understanding it is the same as the generic "automatic"-value. Please correct me if I'm wrong!
- I renamed _model-begin/end_ by the more descriptive _import-begin/end_ and used the ontology-standard date-format for these fields.
- the in CH relevant _type-number_ is included in the form _national-type-code_
- _price-with-tax_ is now an additional property for vehicles
- the "previous-product"-parameters (cancelled by insurer and number of previous claims) included as properties of the product, such that we keep the product-schemas consistent.
 
I'd merge the changes into the master on Thursday.
Please take a look and let me know if you have additional comments! I'm looking forward to your feedback.

Best, Bettina

**Comment by felippewi** [comment]
Hi Bettina, 

thank you for your comments and constructive change proposals. From my point of view, it's looking good. Great work.

Best,
Felippe

**Pull request merged**
